site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences

google_analytics:
  - G-8K4V0F5DTX
  - auto
