site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences 

plugins:
  - search
  - git-revision-date-localized

google_analytics:
  - UA-25246208-6 
  - auto

nav:
  - Main: index.md
  - Concepts: concepts.md
  - Getting Started: getting-started.md
  - XXXX to XXX: xxx.md
  - Release notes: release-notes.md
  - API Documentation: api-doc.md
  - Support: support.md
