site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences 

plugins:
  - search
  - git-revision-date-localized
  - git-committers:
      repository: passarinho4/mkdocs
      branch: main

google_analytics:
  - UA-25246208-6 
  - auto
